server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eso31/configuration-repository
          clone-on-start: true
security:
  user:
    name: root
    password: root
