server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: /home/dcross/Desktop/repo
          clone-on-start: true
security:
  user:
    name: root
    password: root
